### PR TITLE
Integrate googlemaps yelp

### PR DESCRIPTION
**Pull request by evanvas**
**Time Spent: 10 hours**

Features
-GoogleMaps onClick feature to call Yelp API
-Improved Google Maps component to display location without places for UI redesign.

This is the integration of the GoogleMaps and Yelp API. When google maps loads, it displays all locations based on the food that is selected and the address of the user. When clicking on each location google maps sends a specific request to the yelp API to load the restaurants reviews.

### CODE REVIEW

**Review by zhuoyingcai — COMMENTED** [review]
Great job. When I clicked on the restaurant, the corresponding reviews would show under the map. 

But there is a warning after I clicked on the marker on the map.
screen shot 2018-12-02 at 11 55 01 pm
Other than this, everything else works as expected.

**Comment by chc5** [comment]
Just a heads up that this PR includes https://github.com/CSC59939/LunchIn/pull/76

**Review by zhuoyingcai — CHANGES_REQUESTED** [review]
screen shot 2018-12-03 at 3 49 07 pm
screen shot 2018-12-03 at 3 49 33 pm
I clicked on different Dunkin' Donuts, but the yelp reviews did not update. It happens to restaurant chains.

**Review by zhuoyingcai — CHANGES_REQUESTED** [review]
ezgif com-video-to-gif
I clicked on one marker, but it changed automatically to a different restaurant.

**Comment by gerryzqx** [comment]
@chc5 @EvanVasquez Is the above error that @zhuoyingcai pointed out fixed in #89 ? If so, why did you make another PR that fixes this issue? How come you didn't work on it in this PR?

**Comment by chc5** [comment]
The pull request on https://github.com/CSC59939/LunchIn/pull/89 was to update the Reviews UI completely. I asked Evan to merge my own branch to this branch because my branch was written on this branch. For now, I cannot fix this issue with a 100% accuracy because we're relying Yelp to be as accurate as possible with the restaurant's name and location.

**Comment by zhuoyingcai** [comment]
screen shot 2018-12-03 at 10 54 45 pm
The review section looks better now. But I think it's a little small on the bottom. I can't read the entire review and sometimes the profile picture failed to load. 
<br>
Maybe we can just not displaying the profile picture and give more space to the text. @chc5

**Comment by chc5** [comment]
The reviews are purposely cut off by Yelp's API, so there's nothing I can do about it. As for the images, I'll replace it with a blank image.

**Comment by gerryzqx** [comment]
@chc5 You can leave the reviewer picture, just blank out the reviewer picture that doesn't load properly.

**Comment by chc5** [comment]
@zhuoyingcai If everything is okay, please remember to approve this PR.

**Comment by EvanVasquez** [comment]
**Time Spent: 10 hours**

Features
-GoogleMaps onClick feature to call Yelp API
-Improved Google Maps component to display location without places for UI redesign.

**Pull request merged**
