### PR TITLE
Chc Yelp Revisions - Refactor once more for Maps Integration

### PR DESCRIPTION
**Pull request by chc5**
This pull request includes the previous pull requests that I made: https://github.com/CSC59939/LunchIn/pull/72 , https://github.com/CSC59939/LunchIn/pull/75

Additional Updates besides the ones I listed above:
 - Removed BusinessCardList because it's unnecessary for the final release.

Hours Spent: 2

Upcoming Plans:
Redesigning the UI after Evan makes his part of Maps-Yelp integration with this branch.

### CODE REVIEW

**Review by gerryzqx — CHANGES_REQUESTED** [review]
@chc5 Thanks for taking your time and making all these changes! 
Few things I found:
1. When I was running on your branch to test out the changes, I see that it only generate yelp review for one restaurant. I guess you're making it like this so @EvanVasquez can integrate yelp to the map better? 
2. The top 3 reviews for any restaurant selected in yelp comes from the same 3 people (please refer to the images attached), doesn't matter what food was selected or what restaurant was selected.
screen shot 2018-11-29 at 4 01 35 pm
screen shot 2018-11-29 at 4 01 59 pm

**Review by buenoluis007 — COMMENTED** [review]
I ran into the same issue with the reviews that @gerryzqx did in his second point. Same people and same review for all of them. Please fix this bug.

**Comment by chc5** [comment]
This is something that Evan has to set up. This is currently not my task. I don't have the methods Evan have created to select restaurants on Yelp. Please remember that this is a series of consecutive pull requests that ensures that we are heading the right direction.

**Comment by chc5** [comment]
@gerryzqx This is certainly a bug that I had there because I don't have the data that is required to select the restaurant. @EvanVasquez will be in charge of Part 2 of this integration.

**Comment by gerryzqx** [comment]
> This is something that Evan has to set up. This is currently not my task. I don't have the methods Evan have created to select restaurants on Yelp. Please remember that this is a series of consecutive pull requests that ensures that we are heading the right direction.

@chc5 got it, thanks for clarifying! @EvanVasquez please get the methods to set up asap, thanks!

**Pull request closed without merging**
