### PR TITLE
Restructured where files are located in the root branch. 

### PR DESCRIPTION
**Pull request by chc5**
Hours Spent: 4
Notes:
 - I moved all the create-react-app boilerplate files and folders into the client folder.
 - All the modules and frameworks related to React.js will be in the client folder and it is the same for Express.js
 - This version has successfully deployed on to Heroku. https://serene-plateau-21755.herokuapp.com/
 - I have modified the way we call our npm on the root directory on package.json
   1.  `npm run-script dev` will run the entire tech stack on your local machine.
   2.  `npm test` will remain the same.
   3.  `npm start` will not be used to run the app on the local machine and it will be used to run the production build.
   4. `npm run-script client` and `npm run-script server` will run by itself if called separately.

### CODE REVIEW

**Comment by gerryzqx** [comment]
@chc5 Is it possible if you can change the heroku url to something with LunchIn in it?

**Comment by sengfung27** [comment]
@gerryzqx Yes, we can.

**Comment by chc5** [comment]
Yes.

**Comment by chc5** [comment]
It does not seem like the environmental variables are set in Travis.

**Comment by sengfung27** [comment]
@chc5 Can you create a branch instead of doing under your forked branch? Because we want to keep our api keys safe. https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions. Thank you

**Pull request merged**
