### PR TITLE
Chc reviews from yelp

### PR DESCRIPTION
**Pull request by chc5**
Hours Spent: 3
Refactoring: 
 - Renamed Reviews to BusinessCards
 - Reorganized the directories that leads to the BusinessCard directory.
New Functionality:
 - ReviewList: when clicking one of the business cards shown on the website, a list of reviews will appear right on the bottom of that business card.
 - Added unit tests for Review and Review Card.

### CODE REVIEW

**Comment by EvanVasquez** [comment]
The code looks good and runs as intended ! And i agree with the others on the css changes !

**Comment by sengfung27** [comment]
I suggest someone helping Chieh on the css changes. Other than that, looks good and run as I expected

**Comment by chc5** [comment]
UI changes will be our final steps for our second release.

**Comment by chc5** [comment]
I'll keep that in mind when we fix the UI by next week!

**Pull request merged**
